= workstation
ifdef::env-github[]
:imagesdir:
 https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]
:toc:
:toc-placement!:

My complete setup of workstation on a linux system. +
It consist of nixos + home-manager OR home-manager only on non-nixos distros.

toc::[]

== Explanation of setup

*home* folder is home-manger configs for each host

*hosts* folder is nixos configuration.

== Prerequisites
- git (Will use home-manager git after install)
- Repo cloned into /Dev/.workstation folder TODO: Allow any location.

== How to bootstrap

Depending on what OS is being used, either any Linux OS or NIXOS the bootstrapping is a bit different.

=== Other linux distro
Start by installing nix
[source,bash]
----
# Install nix
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

# Make sure flakes enabled  ~/.config/nix/nix.conf with the following line:
experimental-features = nix-command flakes
----

[IMPORTANT]
====
nixos-rebuild `--flake .` defaults to look for nixConfigurations named `hostname`  +
home-manager `--flake .` defaults to look for homeConfigurations named `$(USERNAME)@hostname`

Specify name explicitly when needed e.g. `--flake .#desktop` to use other than default, usefull if this is first setup and hostname is reconfigured later.
====


== First time use
[source, bash]
----
# Run this in repo root if NOT nix-command or flakes.
nix-shell

# If already has nix setup with flakes and nix-command, this run devShell in flake.nix
nix develop
----

.Nixos
[source, bash]
----
# Build system configuration
nixos-rebuild build --flake .

# Build and activate

nixos-rebuild switch --flake .
----

.Other linux distro
[source, bash]
----
# Build system configuration
home-manager build --flake .engson@work

home-manager switch --flake .engson@work
----

== Update configs
[source, bash]
----
# Evaluate flake.nix and check if syntactically is correct
nix flake check

# Reconfigure flake after init 
nix flake update
# Git commit and push changes
----


== Secrets
TODO: Not in use yet
[source,bash]
----
mkdir -p ~/.config/sops/age
# Generate private and public key
nix shell nixpkgs#age -c age-keygen -o ~/.config/sops/age/keys.txt
# Get public key
nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt
----

TODO: Fix non-default home-manager location

== Flakes
[source,bash]
----
nix flake archive - copy a flake and all its inputs to a store 
nix flake check - check whether the flake evaluates and run its tests 
nix flake clone - clone flake repository 
nix flake info - show flake metadata 
nix flake init - create a flake in the current directory from a template 
nix flake lock - create missing lock file entries 
nix flake metadata - show flake metadata 
nix flake new - create a flake in the specified directory from a template 
nix flake prefetch - download the source tree denoted by a flake reference into the Nix store 
nix flake show - show the outputs provided by a flake 
nix flake update - update flake lock file 
----

== Common issues
.flake issue 1
[source,bash]
----
warning: Git tree '<location>' is dirty
error: getting status of '/nix/store/bhrlvs829n0bgg5c2b1q41vysnka9w07-source/2023': No such file or director
# Make sure flake is git committed or not .gitignored
----

.nvidia drivers
[source,bash]
----
# This should run with no errors
nvidia-smi

#You should not see nouveau.
lsmod | grep nvidia
----

nixos-rebuild dry-build --flake .


== References
https://github.com/Misterio77/nix-starter-configs.git

