set -g default-terminal "tmux-256color"

set -g base-index 0
set -g pane-base-index 0

set -g status-keys vi
set -g mode-keys vi

set -g mouse on
set -g focus-events off
set -g aggressive-resize off
set -g clock-mode-style 12
set -s escape-time 500
set -g history-limit 20000


bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
